# Generated by Django 4.1.2 on 2022-11-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticker",
            old_name="keywords",
            new_name="keyword",
        ),
    ]
