# Generated by Django 4.1.2 on 2022-12-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0002_rename_keywords_ticker_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=40)),
                (
                    "ticker_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chart.company"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Ticker",
        ),
    ]
